add step

diff --git a/.drone.yml b/.drone.yml
--- a/.drone.yml
+++ b/.drone.yml
@@ -35,4 +35,21 @@ steps:
   depends_on:
   - check style
 
+- name: run unit tests
+  image: igur007/py3106allure:latest
+  pull: if-not-exists
+  commands:
+  - ls -lha
+  - |
+    # Zip the allure-results folder
+    if [ -d "allure-results" ]; then
+      zip -r allure-results.zip allure-results
+    else
+      echo "allure-results folder not found"
+      exit 1
+    fi
+    
+    # Upload the zip file to the Allure server
+    curl --location --request POST 'http://allure-server.allure-server.svc.cluster.local:8080/api/result' \
+      --form 'allureResults=@"allure-results.zip"'
 
